import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const plugin=path.join(root,'plugins/codex-opencode');
const manifest=JSON.parse(fs.readFileSync(path.join(plugin,'.codex-plugin/plugin.json')));
assert.equal(manifest.name,'codex-opencode'); assert.match(manifest.version,/^\d+\.\d+\.\d+(?:\+.+)?$/);
for(const key of ['description','author','interface','skills','mcpServers']) assert.ok(manifest[key],key);
assert.equal(manifest.skills,'./skills/'); assert.equal(manifest.mcpServers,'./.mcp.json');
assert.ok(!JSON.stringify(manifest).includes('TODO'));
const mcp=JSON.parse(fs.readFileSync(path.join(plugin,'.mcp.json'))); assert.ok(mcp.mcpServers['codex-opencode'].command);
const market=JSON.parse(fs.readFileSync(path.join(root,'.agents/plugins/marketplace.json')));
const entry=market.plugins.find(p=>p.name===manifest.name); assert.equal(entry.source.path,'./plugins/codex-opencode');
assert.equal(entry.policy.installation,'AVAILABLE'); assert.equal(entry.policy.authentication,'ON_INSTALL');
const skill=fs.readFileSync(path.join(plugin,'skills/delegate-opencode/SKILL.md'),'utf8').replaceAll('\r\n','\n');
assert.match(skill,/^---\nname: delegate-opencode\ndescription: .+\n---\n/); assert.ok(!skill.includes('TODO')); assert.ok(skill.split('\n').length<500);
for(const name of ['doctor','submit_tasks','list_runs','get_run','wait_run','get_artifact','review_task','respond_to_request','reconcile_run','cancel_run','validate_run','finalize_run']) assert.ok(skill.includes(name),name);
const interfaceFile=fs.readFileSync(path.join(plugin,'skills/delegate-opencode/agents/openai.yaml'),'utf8'); assert.ok(interfaceFile.includes('$delegate-opencode'));
console.log('Plugin, marketplace and delegation skill contracts validated.');
